repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: detect-aws-credentials
        args: [ '--allow-missing-credentials' ]
  - repo: https://github.com/golangci/golangci-lint
    rev: c0d3ddc9cf3faa61a4e378e879ece580256d76e5  # frozen: v2.12.2
    hooks:
      - id: golangci-lint
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: f298c082154b2cb239fac06a4f452368e66e66dd  # frozen: v1.0.0-rc.4
    hooks:
      - id: go-fmt
      - id: go-imports
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.26.0
    hooks:
      - id: ggshield
        language: python
        stages: [commit]
        args: ["secret", "scan", "pre-commit"]
