// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/honestbank/event-driver/handlers/cache (interfaces: ConflictResolver,KeyExtractor)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_cache.go -package=mocks github.com/honestbank/event-driver/handlers/cache ConflictResolver,KeyExtractor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	event "github.com/honestbank/event-driver/event"
	handlers "github.com/honestbank/event-driver/handlers"
	gomock "go.uber.org/mock/gomock"
)

// MockConflictResolver is a mock of ConflictResolver interface.
type MockConflictResolver struct {
	ctrl     *gomock.Controller
	recorder *MockConflictResolverMockRecorder
}

// MockConflictResolverMockRecorder is the mock recorder for MockConflictResolver.
type MockConflictResolverMockRecorder struct {
	mock *MockConflictResolver
}

// NewMockConflictResolver creates a new mock instance.
func NewMockConflictResolver(ctrl *gomock.Controller) *MockConflictResolver {
	mock := &MockConflictResolver{ctrl: ctrl}
	mock.recorder = &MockConflictResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConflictResolver) EXPECT() *MockConflictResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockConflictResolver) Resolve(arg0 context.Context, arg1 *event.Message, arg2 handlers.CallNext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockConflictResolverMockRecorder) Resolve(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockConflictResolver)(nil).Resolve), arg0, arg1, arg2)
}

// MockKeyExtractor is a mock of KeyExtractor interface.
type MockKeyExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockKeyExtractorMockRecorder
}

// MockKeyExtractorMockRecorder is the mock recorder for MockKeyExtractor.
type MockKeyExtractorMockRecorder struct {
	mock *MockKeyExtractor
}

// NewMockKeyExtractor creates a new mock instance.
func NewMockKeyExtractor(ctrl *gomock.Controller) *MockKeyExtractor {
	mock := &MockKeyExtractor{ctrl: ctrl}
	mock.recorder = &MockKeyExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyExtractor) EXPECT() *MockKeyExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockKeyExtractor) Extract(arg0 *event.Message) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockKeyExtractorMockRecorder) Extract(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockKeyExtractor)(nil).Extract), arg0)
}
